<html>

<head>
	<title>Code</title>
	<link rel="stylesheet"
           href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel="stylesheet" href="style.css">
</head>

<body>
	<pre id="code_snippet"><code>${codeNth.code}</code></pre>
	<span id="load_date"><code>${codeNth.date}</code></span>
</body>

</html>